Snapshotter status report structure update and support for http IPFS URL
PowerLoom/audit-protocol pull request #36
Opened 2023-06-13 08:59 UTC by swagftw

Includes changes from #34 and #35

### Checklist
- [x] My branch is up-to-date with upstream/main branch.
- [x] Everything works and tested for major version of Python/NodeJS/Go and above.
- [x] I ran pre-commit checks against my changes.

### Summary
- Snapshotter status report now has valid `reason` for failure and `snapshot data` for better tracing
- Support for http IPFS URL has been added, eg. `http://localhost:5001` or `https://ipfs.infura.io:5001` are now valid URLs
- Signature deadline has been increased from `10` to `30` in `settings.example.com`

## Deployment Instructions
Increase Signature deadline (`settings.signer.deadlineBuffer` key) to `30`

2023-06-13 11:39 UTC, anomit approved these changes
LGTM

2023-06-13 18:17 UTC, xadahiya requested changes
Noticed these errors upon running it for some time. Please take a look
<img width="1484" alt="Screenshot 2023-06-13 at 11 30 17 PM" src="https://github.com/PowerLoom/audit-protocol/assets/9114274/656da103-d83d-4b04-9ddf-fac87fcadb0f">

2023-06-14 06:54 UTC, swagftw commented
> Noticed these errors upon running it for some time. Please take a look

Issue has been addressed in the PR #38

2023-06-14 07:51 UTC, xadahiya commented on snapshotter_autofill.sh
> +export relayer_host="${RELAYER_HOST:-https://relayer-test1b.powerloom.io}"
@swagftw?? check default relayer

2023-06-14 08:09 UTC, xadahiya approved these changes
New changes seem to have fixed the Rabbitmq channel issues. New code is running without any issues in stg instances for some time now. Approving

<img width="1343" alt="Screenshot 2023-06-14 at 1 36 35 PM" src="https://github.com/PowerLoom/audit-protocol/assets/9114274/43e2ee18-951d-4e4c-ba9f-229fcf28766b">

2023-06-14 08:11 UTC, merged